 - name: Apt Project Playbook
    hosts: elk
    become: true
    tasks:

    - name: Install docker.io httpd (state=present)
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip httpd (state=present)
      apt:
        name: python3-pip
        state: present

    - name: Install docker httpd (state=present)
      pip:
        name: docker
        state: present

    - name: Enable Docker Service (state=present)
      systemd:
            name: docker
            enabled: yes


